name: Build Smoosher

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
  workflow_dispatch:

jobs:
  build:
    name: ${{ matrix.name }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - name: Windows
            os: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Configure CMake
        run: cmake -B build -DCMAKE_BUILD_TYPE=Release

      - name: Build
        run: cmake --build build --config Release

      - name: Package Windows (VST3)
        shell: bash
        run: |
          mkdir -p Smoosher_Distribution/VST3
          cp -r build/Smoosher_artefacts/Release/VST3/Smoosher.vst3 Smoosher_Distribution/VST3/
          cd Smoosher_Distribution
          7z a ../Smoosher-Windows.zip .
          cd ..

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: Smoosher-Windows
          path: Smoosher-Windows.zip
          if-no-files-found: error

  create-release:
    name: Create Release
    needs: build
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/v')

    steps:
      - name: Download all artifacts
        uses: actions/download-artifact@v4

      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          files: Smoosher-Windows/*.zip
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
